fix events

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -146,75 +146,75 @@ services:
       - "8989:8181"
     entrypoint: [ "/bin/sh", "-c", "./migrator -dsn \"$DSN\" -migration-path \"$MIGRATION_PATH\" up && ./sso-service" ]
 
-  jury-db:
-    image: postgres:16
-    container_name: jury-db
-    environment:
-      POSTGRES_USER: jury_user
-      POSTGRES_PASSWORD: jury_pass
-      POSTGRES_DB: JureAssignmentsServiceDB
-    ports:
-      - "5445:5432"
-    networks:
-      - olympic
-    volumes:
-      - jury-db-data:/var/lib/postgresql/data
-    healthcheck:
-      test: [ "CMD-SHELL", "pg_isready -U jury_user -d JureAssignmentsServiceDB" ]
-      interval: 5s
-      timeout: 3s
-      retries: 5
+  # jury-db:
+  #   image: postgres:16
+  #   container_name: jury-db
+  #   environment:
+  #     POSTGRES_USER: jury_user
+  #     POSTGRES_PASSWORD: jury_pass
+  #     POSTGRES_DB: JureAssignmentsServiceDB
+  #   ports:
+  #     - "5445:5432"
+  #   networks:
+  #     - olympic
+  #   volumes:
+  #     - jury-db-data:/var/lib/postgresql/data
+  #   healthcheck:
+  #     test: [ "CMD-SHELL", "pg_isready -U jury_user -d JureAssignmentsServiceDB" ]
+  #     interval: 5s
+  #     timeout: 3s
+  #     retries: 5
 
-  jury-service:
-    build:
-      context: ./Jure-assignments-service
-    container_name: jury-service
-    depends_on:
-      jury-db:
-        condition: service_healthy
-    environment:
-      DSN: "postgres://jury_user:jury_pass@jury-db:5432/JureAssignmentsServiceDB?sslmode=disable"
-      MIGRATION_PATH: "/app/migrations"
-      CONFIG_PATH: "/app/config-yaml/docker.yaml"
-    networks:
-      - olympic
-    ports:
-      - "8383:8090"
-    entrypoint: [ "/bin/sh", "-c", "./migrator -dsn \"$DSN\" -migration-path \"$MIGRATION_PATH\" up && ./jury-ass-service" ]
+  # jury-service:
+  #   build:
+  #     context: ./Jure-assignments-service
+  #   container_name: jury-service
+  #   depends_on:
+  #     jury-db:
+  #       condition: service_healthy
+  #   environment:
+  #     DSN: "postgres://jury_user:jury_pass@jury-db:5432/JureAssignmentsServiceDB?sslmode=disable"
+  #     MIGRATION_PATH: "/app/migrations"
+  #     CONFIG_PATH: "/app/config-yaml/docker.yaml"
+  #   networks:
+  #     - olympic
+  #   ports:
+  #     - "8383:8090"
+  #   entrypoint: [ "/bin/sh", "-c", "./migrator -dsn \"$DSN\" -migration-path \"$MIGRATION_PATH\" up && ./jury-ass-service" ]
 
-  olymp-admin:
-    build:
-      context: .
-      dockerfile: ./docker/php/Dockerfile
-    container_name: olymp-admin
-    ports:
-      - "8083:8083"
-    command:
-      - /bin/sh
-      - -c
-      - |
-        cd /var/www/olymp-admin
-        if [ ! -f .env ]; then
-            cp .env.example .env
-        fi
-        php artisan key:generate
-        composer install --no-interaction --optimize-autoloader
-        while ! nc -z olymp-admin-db 3306; do
-          sleep 1
-        done
-        php artisan migrate:fresh --seed --force
-        php artisan serve --host=0.0.0.0 --port=8083 &
-        php-fpm -F -R &
-        exec php artisan rabbitmq-handler
-    volumes:
-      - ./olymp-admin:/var/www/olymp-admin
-    environment:
-      - DB_HOST=olymp-admin-db
-    depends_on:
-      - olymp-admin-db
-      - rabbitmq
-    networks:
-      - olympic
+  # olymp-admin:
+  #   build:
+  #     context: .
+  #     dockerfile: ./docker/php/Dockerfile
+  #   container_name: olymp-admin
+  #   ports:
+  #     - "8083:8083"
+  #   command:
+  #     - /bin/sh
+  #     - -c
+  #     - |
+  #       cd /var/www/olymp-admin
+  #       if [ ! -f .env ]; then
+  #           cp .env.example .env
+  #       fi
+  #       php artisan key:generate
+  #       composer install --no-interaction --optimize-autoloader
+  #       while ! nc -z olymp-admin-db 3306; do
+  #         sleep 1
+  #       done
+  #       php artisan migrate:fresh --seed --force
+  #       php artisan serve --host=0.0.0.0 --port=8083 &
+  #       php-fpm -F -R &
+  #       exec php artisan rabbitmq-handler
+  #   volumes:
+  #     - ./olymp-admin:/var/www/olymp-admin
+  #   environment:
+  #     - DB_HOST=olymp-admin-db
+  #   depends_on:
+  #     - olymp-admin-db
+  #     - rabbitmq
+  #   networks:
+  #     - olympic
 
   olympic-notification:
     build:
@@ -275,21 +275,21 @@ services:
 #    networks:
 #      - olympic
 
-  olymp-admin-db:
-    image: mariadb:10.11
-    container_name: olymp-admin-db
-    restart: always
-    environment:
-      MYSQL_ROOT_PASSWORD: root
-      MYSQL_DATABASE: olymp_admin
-      MYSQL_USER: root
-      MYSQL_PASSWORD: root
-    ports:
-      - "3306:3306"
-    volumes:
-      - olymp-admin-db_data:/var/lib/mysql
-    networks:
-      - olympic
+  # olymp-admin-db:
+  #   image: mariadb:10.11
+  #   container_name: olymp-admin-db
+  #   restart: always
+  #   environment:
+  #     MYSQL_ROOT_PASSWORD: root
+  #     MYSQL_DATABASE: olymp_admin
+  #     MYSQL_USER: root
+  #     MYSQL_PASSWORD: root
+  #   ports:
+  #     - "3306:3306"
+  #   volumes:
+  #     - olymp-admin-db_data:/var/lib/mysql
+  #   networks:
+  #     - olympic
 
   olymp-notification-db:
     image: mariadb:10.11
@@ -307,20 +307,20 @@ services:
     networks:
       - olympic
 
-  phpmyadmin-admin:
-    image: phpmyadmin:latest
-    container_name: olymp_admin_phpmyadmin
-    restart: always
-    ports:
-      - "8081:80"
-    environment:
-      PMA_HOST: olymp-admin-db
-      PMA_USER: root
-      PMA_PASSWORD: root
-    depends_on:
-      - olymp-admin-db
-    networks:
-      - olympic
+  # phpmyadmin-admin:
+  #   image: phpmyadmin:latest
+  #   container_name: olymp_admin_phpmyadmin
+  #   restart: always
+  #   ports:
+  #     - "8081:80"
+  #   environment:
+  #     PMA_HOST: olymp-admin-db
+  #     PMA_USER: root
+  #     PMA_PASSWORD: root
+  #   depends_on:
+  #     - olymp-admin-db
+  #   networks:
+  #     - olympic
 
   phpmyadmin-notification:
     image: phpmyadmin:latest
@@ -399,15 +399,15 @@ services:
       - olympic
     depends_on:
       - elasticsearch
-  promtail:
-    image: grafana/promtail:2.9.0
-    volumes:
-      - ./promtail-config.yaml:/etc/promtail/config.yml
-      - /var/lib/docker/containers:/var/lib/docker/containers:ro
-      - /var/run/docker.sock:/var/run/docker.sock:ro
-    command: -config.file=/etc/promtail/config.yml
-    networks:
-      - olympic
+  # promtail:
+  #   image: grafana/promtail:2.9.0
+  #   volumes:
+  #     - ./promtail-config.yaml:/etc/promtail/config.yml
+  #     - /var/lib/docker/containers:/var/lib/docker/containers:ro
+  #     - /var/run/docker.sock:/var/run/docker.sock:ro
+  #   command: -config.file=/etc/promtail/config.yml
+  #   networks:
+  #     - olympic
   prometheus:
     image: prom/prometheus:latest
     container_name: olymp_prometheus
@@ -417,24 +417,24 @@ services:
       - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
     networks:
       - olympic
-  loki-init:
-    image: busybox
-    command: ["sh", "-c", "mkdir -p /data/chunks /data/index /data/cache /data/compactor"]
-    volumes:
-      - loki-data:/data
-    restart: "no"
+  # loki-init:
+  #   image: busybox
+  #   command: ["sh", "-c", "mkdir -p /data/chunks /data/index /data/cache /data/compactor"]
+  #   volumes:
+  #     - loki-data:/data
+  #   restart: "no"
 
-  loki:
-    image: grafana/loki:2.9.0
-    depends_on:
-      - loki-init
-    ports:
-      - "3100:3100"
-    volumes:
-      - loki-data:/loki
-    command: -config.file=/etc/loki/local-config.yaml
-    networks:
-      - olympic
+  # loki:
+  #   image: grafana/loki:2.9.0
+  #   depends_on:
+  #     - loki-init
+  #   ports:
+  #     - "3100:3100"
+  #   volumes:
+  #     - loki-data:/loki
+  #   command: -config.file=/etc/loki/local-config.yaml
+  #   networks:
+  #     - olympic
 
 networks:
   olympic:
@@ -442,11 +442,11 @@ networks:
 
 volumes:
   application-db-data:
-  loki-data:
+  # loki-data:
   event-db-data:
   sso-db-data:
-  jury-db-data:
-  olymp-admin-db_data:
+  # jury-db-data:
+  # olymp-admin-db_data:
   olymp-notification-db_data:
   redis_data:
   rabbitmq_data:
